### ISSUE TITLE
Decrypt hwp5

### ISSUE THREAD

**Issue by nvb13** [cogniti/libhwp#3]
Hello,how can i open encrypted hwp file by this lib?

**Comment by cogniti** [comment]
Hello.
Please refer to the https://github.com/cogniti/libhwp/blob/master/utils/hwp2txt.c
You can use `hwp_file_new_for_path()`, `hwp_file_new_for_uri()`.

**Comment by nvb13** [comment]
but hwp file encrypted by password.

**Comment by cogniti** [comment]
No password required.
